import { Platform, StyleSheet } from 'react-native';
export const colors = {
  headerDark: '#1F4F59',  
  headerDarker: '#173D45', 
  primary: '#3AA39F',      
  primaryTint: '#e9fcfb',
  cyan: '#9be5d9',
  olive: '#7EA00E',
  oliveTint: '#F3F6E4',    
  yellowGreen: '#DCD964',
  positive: '#0E7C5A',
  positiveBg: '#E1F5EC',
  danger: '#DC2626',
  textDark: '#0F172A',
  textMuted: '#64748B',
  textFaint: '#94A3B8',
  border: '#E2E8F0',
  surface: '#FFFFFF',
  surfaceMuted: '#F8FAFC',
  background: '#F8FAFC',
  overlay: 'rgba(9, 20, 19, 0.5)',
};

export const categoryThemes = [
  { bg: '#E6F0F2', text: '#1F4F59', iconBg: '#54C9CC', iconColor: '#FFFFFF' },
  { bg: '#F4F8E8', text: '#213502', iconBg: '#7EA00E', iconColor: '#FFFFFF' },
  { bg: '#FAFAD8', text: '#213502', iconBg: '#DCD964', iconColor: '#213502' },
];

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    borderRadius: 12,
  },
  modernHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'android' ? 44 : 20,
    paddingBottom: 20,
    backgroundColor: colors.headerDark,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
  },
  summaryPillsContainer: { gap: 12, marginBottom: 24 },
  summaryPill: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 20,
    borderWidth: 1,
  },
  summaryPillOwed: {
    backgroundColor: colors.positiveBg,
    borderColor: '#B9E6CE',
  },
  summaryPillOwe: {
    backgroundColor: colors.oliveTint,
    borderColor: '#E3E7C2',
  },
  summaryPillLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textMuted,
  },
  summaryPillAmount: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.textDark,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  modernHeaderTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.5,
  },
  quickFormTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.headerDarker,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    gap: 4,
  },
  quickFormTriggerText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
  },
  scrollContent: {
    paddingBottom: 40,
    paddingHorizontal: 24,
    paddingTop: 16,
  },
  friendsSection: {
    marginBottom: 24,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  sectionCount: {
    fontSize: 12,
    color: colors.textMuted,
    fontWeight: '500',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textDark,
    letterSpacing: -0.2,
    paddingBottom: 10,
  },
  horizontalFriendsScroll: {
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarContainer: {
    alignItems: 'center',
    marginRight: 20,
    width: 60,
  },
  addCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1.5,
    borderColor: colors.textFaint,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.surface,
    marginBottom: 6,
  },
  friendAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  avatarLetter: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.headerDark,
  },
  avatarName: {
    fontSize: 12,
    color: colors.textDark,
    fontWeight: '500',
    textAlign: 'center',
  },
  formDrawerContainer: {
    width: '100%',
    maxWidth: 440,
    backgroundColor: colors.surface,
    borderRadius: 28,
    paddingHorizontal: 24,
    paddingTop: 22,
    paddingBottom: 28,
    maxHeight: '86%',
    shadowColor: '#04201C',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.28,
    shadowRadius: 32,
    elevation: 16,
  },
  pullBar: {
    display: 'none',
  },
  drawerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.textDark,
    letterSpacing: -0.3,
  },
  closeCircle: {
    width: 32,
    height: 32,
    // borderRadius: 16,
    // borderWidth: 1,
    // borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textMuted,
    marginTop: 16,
    marginBottom: 6,
  },
  input: {
    borderWidth: 0,
    borderColor: colors.border,
    padding: 12,
    borderRadius: 16,
    backgroundColor: "#0000000c",
    fontSize: 15,
    color: colors.textDark,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceMuted,
    borderRadius: 50,
    padding: 4,
    marginTop: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 25,
  },
  tabBtnActive: {
    backgroundColor: colors.headerDark,
  },
  tabBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textMuted,
  },
  tabBtnTextActive: {
    color: colors.surface,
  },

  inlineChecklist: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
    // backgroundColor: colors.surfaceMuted,
    padding: 12,
    // borderRadius: 14,
    // borderWidth: 1,
    // borderColor: colors.border,
  },
  checkChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.surface,
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  checkChipSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryTint,
  },
  checkChipText: {
    fontSize: 13,
    color: '#475569',
    fontWeight: '500',
  },
  checkChipTextSelected: {
    color: colors.primary,
    fontWeight: '700',
  },
  customSection: {
    marginTop: 16,
    backgroundColor: colors.oliveTint,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E3E7C2',
  },
  customSectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textDark,
    marginBottom: 10,
  },
  customRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
    gap: 12,
  },
  customMemberName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
    flex: 1,
  },
  customInput: {
    borderWidth: 1,
    borderColor: '#ecf1bd',
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingVertical: 7,
    paddingHorizontal: 10,
    width: 90,
    textAlign: 'right',
    fontSize: 14,
    color: colors.textDark,
  },
  emptyInlineText: {
    fontSize: 12,
    color: colors.textFaint,
    fontStyle: 'italic',
    paddingVertical: 8,
  },
  previewBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.positiveBg,
    padding: 14,
    borderRadius: 18,
    gap: 10,
    marginTop: 18,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: '#B9E6CE',
  },
  previewText: {
    fontSize: 13,
    color: colors.positive,
    flex: 1,
    fontWeight: '500',
  },
  submitBtn: {
    backgroundColor: colors.headerDarker,
    padding: 15,
    borderRadius: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 16,
  },
  submitBtnText: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: '600',
  },
  historyCard: {
  backgroundColor: colors.surface,
  padding: 16,
  borderRadius: 16,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 6 },
  shadowOpacity: 0.06,
  shadowRadius: 12,
  marginBottom: 14,
  
},
  historyTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  historyDesc: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textDark,
    letterSpacing: -0.1,
  },
  historyMeta: {
    fontSize: 12,
    color: colors.textMuted,
    lineHeight: 16,
  },
  settleOpenBtn: {
    backgroundColor: colors.headerDark,
    paddingVertical: 9,
    paddingHorizontal: 16,
    borderRadius: 20,
  },
  settleOpenBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  fullySettledBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.positiveBg,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 20,
  },
  fullySettledText: {
    color: colors.positive,
    fontSize: 13,
    fontWeight: '600',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
    gap: 8,
  },
  emptyText: {
    color: colors.textFaint,
    fontSize: 14,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 40,
  },
  modalOverlayCenter: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  alertModalContainer: {
    width: '100%',
    maxWidth: 400,
    maxHeight: '80%',
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 24,
    shadowColor: '#04201C',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.28,
    shadowRadius: 32,
    elevation: 16,
  },
  modalContainer: {
    width: '100%',
    maxWidth: 440,
    backgroundColor: colors.surface,
    borderRadius: 26,
    padding: 24,
    maxHeight: '75%',
    shadowColor: '#04201C',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.28,
    shadowRadius: 32,
    elevation: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.textDark,
    flex: 1,
  },
  modalSub: {
    fontSize: 14,
    color: colors.textMuted,
    marginBottom: 16,
  },
  settleMemberCard: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  settleMemberCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  settleMemberIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  settleMemberAvatarChip: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primaryTint,
    justifyContent: 'center',
    alignItems: 'center',
  },
  settleMemberAvatarChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  
  settleMemberAmountBlock: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  settleMemberAmountLabel: {
    fontSize: 12,
    color: colors.textMuted,
    fontWeight: '600',
  },
  settleMemberAmountValue: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.headerDark,
  },
  settleMemberCTA: {
    backgroundColor: colors.headerDark,
    borderRadius: 24,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settleMemberCTAText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  settleMemberPaidPill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: colors.positiveBg,
    borderRadius: 24,
    paddingVertical: 13,
  },
  settleMemberPaidPillText: {
    color: colors.positive,
    fontSize: 14,
    fontWeight: '700',
  },
  budgetChipOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 14,
    borderRadius: 16,
    marginBottom: 10,
  },
  budgetIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 13,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  budgetTextGroup: {
    flex: 1,
  },
  budgetName: {
    fontSize: 14,
    fontWeight: '700',
  },
  budgetBalance: {
    fontSize: 12,
    marginTop: 2,
    opacity: 0.75,
  },



  rightActionsContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  gap: 8,
},
iconButtonsRow: {
  flexDirection: 'row',
  alignItems: 'center',
  gap: 6,
},
actionIconButton: {
  borderRadius: 8,
  justifyContent: 'center',
  alignItems: 'center',
},

categoryIconContainer: {
  width: 40,
  height: 40,
  borderRadius: 20,
  backgroundColor: '#F1F5F9',
  justifyContent: 'center',
  alignItems: 'center',
},
settleActionBtn: {
  backgroundColor: colors.primary || '#007AFF',
  paddingHorizontal: 10,
  paddingVertical: 6,
  borderRadius: 6,
  justifyContent: 'center',
  alignItems: 'center',
  marginRight: 6,
},
settleActionBtnText: {
  color: '#FFFFFF',
  fontSize: 12,
  fontWeight: '600',
},
settleMainCard: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  backgroundColor: '#ffffff',
  padding: 14,
  borderRadius: 12,
  
},
settleCardDesc: {
  fontSize: 15,
  fontWeight: '700',
  color: '#1E293B',
},
settleCardDate: {
  fontSize: 12,
  color: '#64748B',
  marginTop: 2,
},
settleCardTotalLabel: {
  fontSize: 11,
  color: '#64748B',
  textAlign: 'right',
},
settleCardTotalValue: {
  fontSize: 16,
  fontWeight: '700',
  color: '#0F172A',
},
settleMemberRowCard: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  backgroundColor: '#FFFFFF',
  paddingVertical: 7.5,
  borderRadius: 10,
  
},
settleLeftCol: {
  flexDirection: 'row',
  alignItems: 'center',
  flex: 1.3,
  gap: 10,
},
settleCenterCol: {
  flex: 0.9,
  alignItems: 'center',
},
settleRightCol: {
  flex: 1.1,
  alignItems: 'center',
},
settleSuperRightCol: {
  flex: 0.25,
  alignItems: 'center',
},
settleAvatarChip: {
  width: 34,
  height: 34,
  borderRadius: 17,
  backgroundColor: '#F1F5F9',
  justifyContent: 'center',
  alignItems: 'center',
},
settleAvatarText: {
  fontSize: 14,
  fontWeight: '700',
  color: '#475569',
},
settleMemberName: {
  fontSize: 13,
  fontWeight: '600',
  color: '#1E293B',
},
settleMemberSub: {
  fontSize: 11,
  color: '#64748B',
},
settleAmountText: {
  fontSize: 13,
  fontWeight: '700',
  color: '#0F172A',
},
settlePayButton: {
  backgroundColor: colors.primary,
  paddingHorizontal: 12,
  paddingVertical: 4,
  borderRadius: 6,
},
settlePayButtonText: {
  color: '#FFFFFF',
  fontSize: 12,
  fontWeight: '600',
},
settlePaidPill: {
  flexDirection: 'row',
  alignItems: 'center',
  gap: 4,
  backgroundColor: '#F0FDF4',
  paddingHorizontal: 8,
  paddingVertical: 5,
  borderRadius: 6,
},
settlePaidPillText: {
  color: colors.positive,
  fontSize: 12,
  fontWeight: '600',
},
settleOwnerBadge: {
  backgroundColor: '#F1F5F9',
  paddingHorizontal: 8,
  paddingVertical: 4,
  borderRadius: 6,
},
settleOwnerBadgeText: {
  fontSize: 11,
  fontWeight: '600',
  color: '#64748B',
},
settleAvatarImage: {
  width: 34,
  height: 34,
  borderRadius: 17,
  backgroundColor: '#F1F5F9',
},

paymentModalContainer: {
  width: '88%',
  maxWidth: 380,
  backgroundColor: '#FFFFFF',
  borderRadius: 16,
  padding: 22,
},
paymentModalHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: 14,
},
paymentModalTitleRow: {
  flexDirection: 'row',
  alignItems: 'center',
  gap: 8,
},
paymentIconContainer: {
  backgroundColor: '#54C9CC15', // o colors.primary + '15'
  padding: 8,
  borderRadius: 10,
},
paymentModalMainTitle: {
  fontSize: 18,
  fontWeight: '700',
  color: '#1E293B',
},
paymentInfoCard: {
  backgroundColor: '#F8FAFC',
  borderRadius: 12,
  padding: 12,
  marginBottom: 16,
  borderWidth: 1,
  borderColor: '#E2E8F0',
},
paymentCardLabel: {
  fontSize: 13,
  color: '#64748B',
},
paymentFriendName: {
  fontSize: 16,
  fontWeight: '700',
  color: '#1E293B',
  marginTop: 2,
  marginBottom: 8,
},
paymentCardDivider: {
  height: 1,
  backgroundColor: '#E2E8F0',
  marginVertical: 6,
},
paymentBalanceRow: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginTop: 4,
},
paymentOwedAmount: {
  fontSize: 15,
  fontWeight: '700',
  color: '#EF4444',
},
paymentInput: {
  fontSize: 18,
  fontWeight: '600',
  textAlign: 'center',
  backgroundColor: '#FFFFFF',
  borderRadius: 10,
  borderWidth: 1,
  borderColor: '#CBD5E1',
  padding: 12,
},
paymentSubmitBtn: {
  marginTop: 20,
  backgroundColor: '#3AA39F', // o colors.primary
  borderRadius: 10,
  flexDirection: 'row',
  justifyContent: 'center',
  alignItems: 'center',
  gap: 6,
  paddingVertical: 12,
},
paymentSubmitBtnText: {
  color: '#FFFFFF',
  fontSize: 15,
  fontWeight: '600',
},
largeAmountInput: {
  fontSize: 32,
  fontWeight: '700',
  color: colors.textDark, // Adjust to your theme's primary text color
  borderBottomWidth: 2,
  borderBottomColor: colors.primary,
  paddingVertical: 8,
  marginBottom: 16,
},
horizontalChecklist: {
  flexDirection: 'row',
  gap: 8,
  paddingVertical: 4,
  paddingRight: 16,
  marginBottom: 16,
},
});